// std import
const std = @import("std");
const builtin = @import("builtin");

// common import
const common = @import("../common/main.zig");
const BitBoard = common.bit_board.BitBoard(9, 9);

// internal import
const main = @import("./main.zig");
const Game = main.Game;
const Board = main.Board;

test "Board.init: 初期状態のボードを作成する" {
    const board = Board.init();

    try BitBoard.expect(board.black_king,
        \\....o....
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
    );

    try BitBoard.expect(board.white_pawn,
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\ooooooooo
        \\.........
        \\.........
    );
}

test "Board.fromString: 初期状態のボードを作成する" {
    const board = Board.fromString(
        \\lnsgkgtom
        \\.r.h.d.b.
        \\ppppqqqqq
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
    );

    try BitBoard.expect(board.black_king,
        \\....o....
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
    );

    try BitBoard.expect(board.black_rook,
        \\.........
        \\.o.......
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
    );

    try BitBoard.expect(board.black_rook_promoted,
        \\.........
        \\.....o...
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
    );

    try BitBoard.expect(board.black_bishop,
        \\.........
        \\.......o.
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
    );

    try BitBoard.expect(board.black_bishop_promoted,
        \\.........
        \\...o.....
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
    );

    try BitBoard.expect(board.black_gold,
        \\...o.o...
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
    );

    try BitBoard.expect(board.black_silver,
        \\..o......
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
    );

    try BitBoard.expect(board.black_silver_promoted,
        \\......o..
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
    );

    try BitBoard.expect(board.black_knight,
        \\.o.......
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
    );

    try BitBoard.expect(board.black_knight_promoted,
        \\.......o.
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
    );

    try BitBoard.expect(board.black_lance,
        \\o........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
    );

    try BitBoard.expect(board.black_lance_promoted,
        \\........o
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
    );

    try BitBoard.expect(board.black_pawn,
        \\.........
        \\.........
        \\oooo.....
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
    );

    try BitBoard.expect(board.black_pawn_promoted,
        \\.........
        \\.........
        \\....ooooo
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
    );
}

test "Board.getPieceAt: 駒の種類を取得する" {
    const board = Board.init();

    try std.testing.expectEqual(Game.Square.white_silver, board.getPieceAt(BitBoard.fromString(
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\......o..
    , 'o')));
}

test "Board.getColorPieces: プレイヤーの駒のすべての位置を取得する" {
    const board = Board.init();

    try BitBoard.expect(board.getColorPieces(.black),
        \\ooooooooo
        \\.o.....o.
        \\ooooooooo
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
    );

    try BitBoard.expect(board.getColorPieces(.white),
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\.........
        \\ooooooooo
        \\.o.....o.
        \\ooooooooo
    );
}
