// std import
const std = @import("std");
const builtin = @import("builtin");

// common import
const common = @import("../common/main.zig");
const BitBoard = common.bit_board.BitBoard(8, 8);

// internal import
const Board = @import("./Board.zig");

test "📖Board.moveMutate: 黒を動かす" {
    var board = Board.fromString(
        \\o..o..o.
        \\.x.x.x..
        \\..xxx...
        \\oxx.xxxo
        \\..xxx...
        \\.x.x.x..
        \\o..x..x.
        \\...o...o
    );

    const place = BitBoard.fromString(
        \\........
        \\........
        \\........
        \\...o....
        \\........
        \\........
        \\........
        \\........
    , 'o');

    const expected = Board.fromString(
        \\o..o..o.
        \\.o.o.o..
        \\..ooo...
        \\oooooooo
        \\..ooo...
        \\.o.o.o..
        \\o..o..o.
        \\...o...o
    );

    board.moveMutate(place);

    try std.testing.expectEqualDeep(expected, board);
}

test "get valid move" {
    // 現在のボード状態
    const board = Board.fromString(
        \\...x..x.
        \\.x.x.x..
        \\..xxx...
        \\.xxoxxxx
        \\...x....
        \\.x.x.x..
        \\.xxxxxxo
        \\........
    );

    // マスク
    // 相手の石があるところだけ + 端をループしないように止める
    const mask = board.boards.get(.white).masks(BitBoard.west_mask.masks(BitBoard.east_mask));

    try mask.expect(
        \\...o..o.
        \\.o.o.o..
        \\..ooo...
        \\.oo.ooo.
        \\...o....
        \\.o.o.o..
        \\.oooooo.
        \\........
    );

    var flip = board.boards.get(.black);
    const dir = 1;

    try flip.expect(
        \\........
        \\........
        \\........
        \\...o....
        \\........
        \\........
        \\.......o
        \\........
    );

    // dirで決められた方向に向けて石を置く
    // 正の方向と負の方向の2方向を同時に進める
    flip = flip.shl(dir).unions(flip.shr(dir)).masks(mask);

    try flip.expect(
        \\........
        \\........
        \\........
        \\..o.o...
        \\........
        \\........
        \\......o.
        \\........
    );

    // さらに進めたものを前回のものとORで重ねる
    flip.setUnion(flip.shl(dir).unions(flip.shr(dir)).masks(mask));

    try flip.expect(
        \\........
        \\........
        \\........
        \\.oo.oo..
        \\........
        \\........
        \\.....oo.
        \\........
    );

    // 合計で6回進める
    flip.setUnion(flip.shl(dir).unions(flip.shr(dir)).masks(mask));
    flip.setUnion(flip.shl(dir).unions(flip.shr(dir)).masks(mask));
    flip.setUnion(flip.shl(dir).unions(flip.shr(dir)).masks(mask));
    flip.setUnion(flip.shl(dir).unions(flip.shr(dir)).masks(mask));

    try flip.expect(
        \\........
        \\........
        \\........
        \\.oo.ooo.
        \\........
        \\........
        \\.oooooo.
        \\........
    );

    // 最後にマスクなしで進める
    // 自分の石の隣に相手の石が繋がっているものの一番先頭

    flip = flip.shl(dir).unions(flip.shr(dir));

    try flip.expect(
        \\........
        \\........
        \\........
        \\oooooooo
        \\........
        \\........
        \\oooooooo
        \\........
    );

    // これを「石が置かれていない場所」でマスク
    flip = flip.excludes(board.boards.get(.black).unions(board.boards.get(.white)));

    try flip.expect(
        \\........
        \\........
        \\........
        \\o.......
        \\........
        \\........
        \\o.......
        \\........
    );

    // これを縦横斜めの4方向に向ける
    try board.getValidMoves().expect(
        \\o.......
        \\........
        \\........
        \\o.......
        \\........
        \\........
        \\o.......
        \\...o....
    );
}

test "get valid move 1" {
    const board = Board.fromString(
        \\.ox.....
        \\........
        \\........
        \\.oxxx...
        \\........
        \\......ox
        \\........
        \\oxxxxxx.
    );

    try board.getValidMoves().expect(
        \\...o....
        \\........
        \\........
        \\.....o..
        \\........
        \\........
        \\........
        \\.......o
    );
}

test "get valid move 2" {
    const board = Board.fromString(
        \\.o...x..
        \\.x.o.o.x
        \\...x...x
        \\...x...x
        \\...x...x
        \\o......x
        \\.......x
        \\.......o
    );

    try board.getValidMoves().expect(
        \\.......o
        \\........
        \\.o......
        \\........
        \\........
        \\...o....
        \\........
        \\........
    );
}

test "get valid move 3" {
    const board = Board.fromString(
        \\o.......
        \\.x...o..
        \\..x...x.
        \\...x....
        \\....x...
        \\.x...x..
        \\..x...x.
        \\o..o....
    );

    try board.getValidMoves().expect(
        \\........
        \\........
        \\........
        \\.......o
        \\o.......
        \\........
        \\........
        \\.......o
    );
}

test "get valid move 4" {
    const board = Board.fromString(
        \\..x.....
        \\.x....x.
        \\o....x..
        \\....x..o
        \\...x..x.
        \\..x..x..
        \\.x..x...
        \\o.......
    );

    try board.getValidMoves().expect(
        \\.......o
        \\........
        \\........
        \\........
        \\........
        \\........
        \\........
        \\...o....
    );
}

test "game is end" {
    const board = Board.fromString(
        \\oooooooo
        \\xxxxxxxx
        \\oooooooo
        \\xxxxxxxx
        \\oooooooo
        \\xxxxxxxx
        \\oooooooo
        \\xxxxxxxx
    );

    try std.testing.expect(board.isEnd());
}

test "game is not end" {
    const board = Board.fromString(
        \\oooooooo
        \\xxxxxxxx
        \\oooooooo
        \\xxxxxxxx
        \\ooo.oooo
        \\xxxxxxxx
        \\oooooooo
        \\xxxxxxxx
    );

    try std.testing.expect(!board.isEnd());
}

test "board from string" {
    const expected = Board{
        .boards = Board.ColorBoards.init(.{
            .black = BitBoard.fromInteger(0x00_00_00_00_00_aa_55_aa),
            .white = BitBoard.fromInteger(0x55_aa_55_00_00_00_00_00),
        }),
    };

    const actual = Board.fromString(
        \\.o.o.o.o
        \\o.o.o.o.
        \\.o.o.o.o
        \\........
        \\........
        \\x.x.x.x.
        \\.x.x.x.x
        \\x.x.x.x.
    );

    try std.testing.expectEqualDeep(expected, actual);
}
