name: Check lint format build and test

on:
  pull_request:
    branches: ["main"]

  workflow_dispatch:

concurrency:
  group: "check"
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - # https://github.com/actions/checkout
        name: Checkout
        uses: actions/checkout@v4

      - # https://github.com/oven-sh/setup-bun
        name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Bun Dependencies
        run: bun install --frozen-lockfile

      - # https://github.com/mlugg/setup-zig
        name: Install Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0

      - run: bun run ci
